# OLIST Analysis
Data From: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

This Notebook I will be merging all data together (9 Files), and diving into the data to see what kind of information I can extract. I am curious about:
* Which States/Cities generate the most revenue? What are the products or categories that accounts for that?

Merging Using:
![](../assets/schema.png)

## Intro

In [2]:
# Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm

In [4]:
# Data
orders_df = pd.read_csv('../data/raw/olist_orders_dataset.csv')
items_df = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
payments_df = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
customers_df = pd.read_csv('../data/raw/olist_customers_dataset.csv')
reviews_df = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
sellers_df = pd.read_csv('../data/raw/olist_sellers_dataset.csv')
products_df = pd.read_csv('../data/clean/products_clean.csv')
location_df = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')

print(f"orders_df has {orders_df.shape[0]} rows and {orders_df.shape[1]} columns.")
print(f"items_df has {items_df.shape[0]} rows and {items_df.shape[1]} columns.")
print(f"payments_df has {payments_df.shape[0]} rows and {payments_df.shape[1]} columns.")
print(f"customers_df has {customers_df.shape[0]} rows and {customers_df.shape[1]} columns.")
print(f"reviews_df has {reviews_df.shape[0]} rows and {reviews_df.shape[1]} columns.")
print(f"sellers_df has {sellers_df.shape[0]} rows and {sellers_df.shape[1]} columns.")
print(f"products_df has {products_df.shape[0]} rows and {products_df.shape[1]} columns.")
print(f"location_df has {location_df.shape[0]} rows and {location_df.shape[1]} columns.")

orders_df has 99441 rows and 8 columns.
items_df has 112650 rows and 7 columns.
payments_df has 103886 rows and 5 columns.
customers_df has 99441 rows and 5 columns.
reviews_df has 99224 rows and 7 columns.
sellers_df has 3095 rows and 4 columns.
products_df has 32951 rows and 12 columns.
location_df has 1000163 rows and 5 columns.

In [23]:
# Merge
df = pd.merge(orders_df, reviews_df, on='order_id', how='left') # left join
df = pd.merge(df, payments_df, on='order_id', how='outer') # one order doesn't have payment info
df = pd.merge(df, customers_df, on='customer_id', how='inner')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,...,review_creation_date,review_answer_timestamp,payment_sequential,payment_type,payment_installments,payment_value,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4.0,...,2017-10-11 00:00:00,2017-10-12 03:43:48,1.0,credit_card,1.0,18.12,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4.0,...,2017-10-11 00:00:00,2017-10-12 03:43:48,3.0,voucher,1.0,2.00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4.0,...,2017-10-11 00:00:00,2017-10-12 03:43:48,2.0,voucher,1.0,18.59,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,8d5266042046a06655c8db133d120ba5,4.0,...,2018-08-08 00:00:00,2018-08-08 18:37:50,1.0,boleto,1.0,141.46,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,e73b67b67587f7644d5bd1a52deb1b01,5.0,...,2018-08-18 00:00:00,2018-08-22 19:07:58,1.0,credit_card,3.0,179.12,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,e262b3f92d1ce917aa412a9406cf61a6,5.0,...,2017-03-22 00:00:00,2017-03-23 11:02:08,1.0,credit_card,3.0,85.08,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP
104474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,29bb71b2760d0f876dfa178a76bc4734,4.0,...,2018-03-01 00:00:00,2018-03-02 17:50:01,1.0,credit_card,3.0,195.00,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP
104475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,371579771219f6db2d830d50805977bb,5.0,...,2017-09-22 00:00:00,2017-09-22 23:10:57,1.0,credit_card,5.0,271.01,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA
104476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,8ab6855b9fe9b812cd03a480a25058a1,2.0,...,2018-01-26 00:00:00,2018-01-27 09:16:56,1.0,credit_card,4.0,441.16,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
104477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,dc9c59b4688062c25758c2be4cafc523,5.0,...,2018-03-17 00:00:00,2018-03-17 16:33:31,1.0,debit_card,1.0,86.86,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR

In [15]:
df.isna().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                  176
order_delivered_carrier_date      1898
order_delivered_customer_date     3154
order_estimated_delivery_date        0
review_id                          800
review_score                       800
review_comment_title             92482
review_comment_message           61662
review_creation_date               800
review_answer_timestamp            800
payment_sequential                   1
payment_type                         1
payment_installments                 1
payment_value                        1
dtype: int64

In [16]:
# Checking which order doesn't have payment information
df[df['payment_installments'].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,payment_sequential,payment_type,payment_installments,payment_value
32304,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,6916ca4502d6d3bfd39818759d55d536,1.0,NaN,nao recebi o produto e nem resposta da empresa,2016-10-06 00:00:00,2016-10-07 18:32:28,NaN,NaN,NaN,NaN